version: '3.4'

services:
  sql.data:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433" 

  dwp.ms.demo.registration:
    image: ${DOCKER_REGISTRY-}dwpmsdemoregistration
    build:
      context: .
      dockerfile: dwp.ms.demo.registration/Dockerfile
    depends_on:
      - sql.data
