apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: vehicle-data
  name: vehicle-data-front
spec:
  type: LoadBalancer
  ports:
  - port: 1431
  selector:
    io.kompose.service: vehicle-data
status:
  loadBalancer: {}
