apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: dwp-ms-demo-registration
  name: dwp-ms-demo-registration
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: dwp-ms-demo-registration
    spec:
      containers:
      - image: dwpdemoacr.azurecr.io/dwpmsdemoregistration:latest
        name: dwp-ms-demo-registration
        ports:
            - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
