apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: dwp-ms-demo-registration
  name: dwp-ms-demo-registration
spec:
  type: LoadBalancer
  ports:
  - port: 1432
    targetPort: 80
  selector:
    io.kompose.service: dwp-ms-demo-registration
status:
  loadBalancer: {}



