apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: sql-data
  name: sql-data
spec:
  ports:
  - name: "5433"
    port: 5433
    targetPort: 1433
  selector:
    io.kompose.service: sql-data
status:
  loadBalancer: {}
