apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: vehicle-data
  name: vehicle-data
spec:
  ports:
  - name: "5434"
    port: 5434
    targetPort: 1433
  selector:
    io.kompose.service: vehicle-data
status:
  loadBalancer: {}
