apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: vehicle-data
  name: vehicle-data
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: vehicle-data
    spec:
      containers:
      - env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_PID
          value: Express
        - name: SA_PASSWORD
          value: Pass@word
        image: mcr.microsoft.com/mssql/server:2017-latest
        name: vehicle-data
        ports:
        - containerPort: 1433
        resources: {}
      restartPolicy: Always
status: {}
