apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: vehicle-data
  name: vehicle-data-front
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433
  selector:
    io.kompose.service: vehicle-data
status:
  loadBalancer: {}
